require:
- rubocop-minitest
- rubocop-performance
- rubocop-rake

AllCops:
  TargetRubyVersion: 2.4

Metrics/AbcSize:
  Max: 60

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/MethodLength:
  Max: 40

Metrics/PerceivedComplexity:
  Max: 20
